seed: 0

df_train_noisy:
  strategy: KeepJustExamplesWithOneClass

dataset:
  downsample_noisy: 0.25
  wav2im_cfg_hash: a38f60a75aec1a6d
  kaggle_valid_set: True

train_batch_size: 64
valid_batch_size: 128
net_module: basic_conv_skip
net_params:
  use_custom_init: False

training:
  lr: 0.002
  scheduler: none
  optimizer: Adam
